Repository jsdrupal/drupal-admin-ui, pull requests merged in 2018-07, with the labels that each got.

#166 Boolean checkbox widget
  src/components/02_atoms/Widgets/BooleanCheckbox.js
  src/components/05_pages/NodeForm/UiMetadata.js
  src/components/05_pages/NodeForm/Widgets.js
Labels: Needs Work 💻

#175 Added OptionsSelect component
  src/components/02_atoms/Widgets/OptionsSelect.js
  src/components/05_pages/NodeForm/UiMetadata.js
  src/components/05_pages/NodeForm/Widgets.js
  src/components/05_pages/NodeForm/index.js
Labels: Enhancement 🎉, Needs Work 💻

#200 Modified number to include suffix and prefix
  src/components/02_atoms/Widgets/NumberTextfield.js
  src/components/05_pages/NodeForm/UiMetadata.js
  src/components/05_pages/NodeForm/index.js
Labels: Enhancement 🎉

#230 Don't render additional widget props as HTML field attributes
  src/components/02_atoms/Widgets/BooleanCheckbox.js
Labels: Bug 🐛

#239 Added openapi to list of dependencies
  admin_ui_support/admin_ui_support.info.yml
Labels: Admin UI Support Module 📜, Bug 🐛

#201 For screenreaders and a11y fix the menu bar.
  src/components/06_wrappers/Default/Default.js
  src/tests/Nightwatch/Tests/menu.js
Labels: Needs Work 💻

#240 Disable actions menu item when no nodes are selected.
  src/components/05_pages/Content/Content.js
Labels: Enhancement 🎉

#187 Add a story book entry for all 'atoms'
  .storybook/addons.js
  src/components/02_atoms/FileUpload/FileUpload.stories.js
  src/components/02_atoms/Widgets/Widgets.stories.js
Labels: Needs Work 💻

#248 Hide react-axe behind an environment variable.
  README.md
  src/index.js
Labels: Bug 🐛

#218 Entity Reference Widget
  package.json
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/05_pages/NodeForm/UiMetadata.js
  src/components/05_pages/NodeForm/Widgets.js
  src/utils/api/api.js
  yarn.lock
Labels: Enhancement 🎉, Needs Work 💻

#246 Fix document.title formatting
  src/components/02_atoms/PageTitle/PageTitle.js
Labels: Bug 🐛
