Repository jsdrupal/drupal-admin-ui, pull requests merged in 2018-08, with the labels that each got.

#171 Enable Node Save
  src/actions/content.js
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/05_pages/NodeForm/RecipeSchema.js
  src/components/05_pages/NodeForm/index.js
  src/utils/api/api.js
  src/utils/api/schema.js
  src/utils/api/schema.test.js
Labels: Enhancement 🎉

#259 Fetch a single document.
  src/actions/content.js
  src/components/05_pages/NodeForm/index.js
  src/reducers/content.js
  src/utils/api/api.js
Labels: Enhancement 🎉

#260 Automatically construct UISchema
  src/actions/content.js
  src/actions/index.js
  src/actions/schema.js
  src/components/02_atoms/FileUpload/FileUpload.js
  src/components/02_atoms/Widgets/BooleanCheckbox.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/05_pages/NodeForm/UiMetadata.js
  src/components/05_pages/NodeForm/Widgets.js
  src/components/05_pages/NodeForm/index.js
  src/reducers/content.js
  src/reducers/index.js
  src/reducers/schema.js
  src/routes.js
  src/utils/api/api.js
  src/utils/api/schema.js
Labels: Enhancement 🎉

#306 Adjust name of `datetime` widget
  src/components/02_atoms/Widgets/DatetimeTimestamp.js
  src/components/02_atoms/Widgets/Widgets.stories.js
  src/components/05_pages/NodeForm/Widgets.js
Labels: Bug 🐛

#292 Secondary column support
  src/components/02_atoms/FileUpload/FileUpload.js
  src/components/02_atoms/Widgets/BooleanCheckbox.js
  src/components/02_atoms/Widgets/DatetimeTimestamp.js
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/02_atoms/Widgets/NumberTextfield.js
  src/components/02_atoms/Widgets/OptionsSelect.js
  src/components/02_atoms/Widgets/StringTextfield.js
  src/components/05_pages/NodeForm/index.js
  src/utils/api/schema.js
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#320 NodeForm initialisation generates warnings(#319)
  src/components/05_pages/NodeForm/index.js
Labels: Bug 🐛

#316 Fix bug in getItemsAsArray().
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/02_atoms/Widgets/Widgets.stories.js
  src/utils/api/fieldItem.js
Labels: Bug 🐛

#290 Mark fields as required
  src/components/02_atoms/Widgets/BooleanCheckbox.js
  src/components/02_atoms/Widgets/DatetimeTimestamp.js
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/02_atoms/Widgets/NumberTextfield.js
  src/components/02_atoms/Widgets/OptionsSelect.js
  src/components/02_atoms/Widgets/StringTextfield.js
  src/components/05_pages/NodeForm/index.js
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#323 Initial draft.js based editor
  package.json
  src/components/02_atoms/Widgets/TextTextarea.js
  src/components/02_atoms/Widgets/Widgets.stories.js
  src/components/05_pages/NodeForm/Widgets.js
  yarn.lock
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#315 Add loading bar component to Content Listing & Node Form pages.
  src/components/05_pages/Content/Content.js
  src/components/05_pages/NodeForm/index.js
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#337 Cleanup console errors due to bad props and PropType checking.
  src/components/02_atoms/Widgets/BooleanCheckbox.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
Labels: Bug 🐛

#351 Make node title a link
  src/components/05_pages/Content/Content.js
Labels: Demo Branch ✅, Drupal Europe Demo ✨, Enhancement 🎉

#336 Use human readable names on Options Select widget.
  src/actions/schema.js
  src/components/02_atoms/Widgets/OptionsSelect.js
  src/components/05_pages/NodeForm/index.js
  src/reducers/schema.js
  src/utils/api/api.js
  src/utils/api/schema.js
Labels: Demo Branch ✅, Drupal Europe Demo ✨, Enhancement 🎉

#353 Move created and uid fields to the right column on node form
  src/components/05_pages/NodeForm/index.js
Labels: Demo Branch ✅, Drupal Europe Demo ✨, Enhancement 🎉

#289 General use "Snackbar" component
  src/actions/application.js
  src/actions/content.js
  src/actions/reports.js
  src/actions/reports.test.js
  src/actions/roles.js
  src/actions/schema.js
  src/components/02_atoms/InlineMessage/InlineMessage.js
  src/components/02_atoms/InlineMessage/InlineMessage.stories.js
  src/components/02_atoms/Message/Message.js
  src/components/02_atoms/Message/Message.stories.js
  src/components/02_atoms/SnackbarMessage/SnackbarMessage.js
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/05_pages/Permissions/Permissions.js
  src/components/06_wrappers/Default/Default.js
  src/components/06_wrappers/ErrorBoundary/ErrorBoundary.js
  src/components/06_wrappers/ErrorBoundary/ErrorBoundary.test.js
  src/constants/messages.js
  src/reducers/application.js
Labels: Enhancement 🎉

#348 Use Drupal route pattern for edits
  src/actions/content.js
  src/components/02_atoms/PageTitle/PageTitle.js
  src/components/05_pages/Content/Content.js
  src/components/05_pages/NodeEditForm/index.js
  src/reducers/content.js
  src/routes.js
Labels: Demo Branch ✅, Drupal Europe Demo ✨, Enhancement 🎉

#372 Add missing message severity on add content error
  src/actions/content.js
Labels: Bug 🐛

#376 Make type check in PageTitle component more accurate
  src/components/02_atoms/PageTitle/PageTitle.js
Labels: Bug 🐛

#379 Fix minor issues with NodeEdit component
  src/components/05_pages/NodeEditForm/index.js
Labels: Drupal Europe Demo ✨

#367 Set a default for authored by field.
  src/actions/content.js
  src/components/05_pages/NodeForm/index.js
  src/reducers/content.js
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#397 Set default created on date.
  src/components/02_atoms/Widgets/DatetimeTimestamp.js
  src/components/05_pages/NodeForm/index.js
Labels: Enhancement 🎉

#357 First iteration of adding support for restoring entity forms
  package.json
  src/App.js
  src/actions/content.js
  src/components/02_atoms/Widgets/EntityReferenceAutocomplete.js
  src/components/02_atoms/Widgets/FileUploadWidget.js
  src/components/02_atoms/Widgets/TextTextarea.js
  src/components/05_pages/NodeAddForm/index.js
  src/components/05_pages/NodeForm/index.js
  src/reducers/content.js
  src/reducers/index.js
  src/tests/Nightwatch/Tests/NodeAdd.js
  yarn.lock
Labels: Drupal Europe Demo ✨, Enhancement 🎉

#396 Show an alert when you have missing fields
  src/components/05_pages/NodeForm/index.js
Labels: Enhancement 🎉

#425 Move the createEntity call to the node add form
  src/components/05_pages/NodeAddForm/index.js
  src/components/05_pages/NodeForm/index.js
Labels: Enhancement 🎉

#439 Fix Nightwatch failure on CircleCI.
  src/tests/Nightwatch/Tests/NodeEdit.js
Labels: Bug 🐛
