Repository jsdrupal/drupal-admin-ui, pull requests merged in 2018-04, with the labels that each got.

#91 Move role/permission fetching and posting into api && make the module compatible with jsonapi 1.15
  admin_ui_support/src/Controller/JsonApiRequestHandler.php
  src/components/05_pages/Permissions/Permissions.js
  src/utils/api/api.js
Labels: Bug 🐛

#93 Add controller to return dblog types (try 2)
  admin_ui_support/admin_ui_support.routing.yml
  admin_ui_support/src/Controller/DbLogTypes.php
Labels: Enhancement 🎉

#90 Upate favicon
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
Labels: Enhancement 🎉, Needs Work 💻

#95 Add configuration option to disable redirecting routes.
  admin_ui_support/admin_ui_support.links.menu.yml
  admin_ui_support/admin_ui_support.routing.yml
  admin_ui_support/admin_ui_support.services.yml
  admin_ui_support/config/install/admin_ui_support.settings.yml
  admin_ui_support/config/schema/admin_ui_support.schema.yml
  admin_ui_support/src/Form/SettingsForm.php
  admin_ui_support/src/Routing/RouteSubscriber.php
  admin_ui_support/tests/src/Functional/RedirectRoutesTest.php
Labels: Enhancement 🎉, Needs Review 📄

#78 Dblog component
  admin_ui_support/admin_ui_support.routing.yml
  package.json
  src/actions/index.js
  src/actions/reports.js
  src/actions/reports.test.js
  src/components/05_pages/Reports/Dblog.js
  src/reducers/application.js
  src/routes.js
  src/utils/api/api.js
  yarn.lock
Labels: Enhancement 🎉
